### ISSUE TITLE
Cliente de comunicación para arrancar

### ISSUE THREAD

**Issue by neydroid** [javascriptnicaragua/js.ni#2]
Qué usaremos para comunicarnos? mí propuesta es Slack, sé que en su momento lo hablamos, pero no aterrizamos en usarlo, escucho sus opiniones y contrapropuestas 😎 @paulomcnally @oscarmcm @amosrivera

**Comment by oscarmcm** [comment]
Slack por el ambito de community y facilidad de usarlo

**Comment by neydroid** [comment]
Necesitamos un voto más @paulomcnally @amosrivera

**Comment by paulomcnally** [comment]
Si esperamos el voto de  @amosrivera llegaremos a la era de que JavaScript se deprecia y descontinua haha.

No hay vuelta de oja. Slack

**Comment by neydroid** [comment]
Corrales, ya @oscarmcm estaba dentro del slack javascriptnicaragua faltan @paulomcnally @amosrivera

**Comment by amosrivera** [comment]
Sorry no había visto este mail :sweat_smile:. Uso Slack todos los días. Para mí es lo mejor. Por donde me meto? :D @paulomcnally @neydroid @oscarmcm

**Comment by oscarmcm** [comment]
@amosrivera ==> javascriptnicaragua.slack.com

**Comment by amosrivera** [comment]
@oscarmcm si pues pero no esta el sign up page, asumo que esta como privado. Ya puse mi mail en 'olvide mi contraseña' pero me dice que no estoy asociado.

**Comment by oscarmcm** [comment]
Ahh!! ahi es con @neydroid aunque creo que ya te había invitado :tada:

**Comment by neydroid** [comment]
revisando, pero los había invitado a todos!
